version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.1
    - 6.2.1
    - 6.2.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.15
    - 13.0.3
    - 13.0.7
    - 13.1.5
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-graphql"
    versions:
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
