sudo: false

language: node_js

node_js:
  - "11"

cache:
  yarn: true
  directories:
    - node_modules
    - .jest/cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - yarn add --dev https://github.com/GoogleChromeLabs/lighthousebot

before_script:
  - yarn danger ci

script:
   - jest --runInBand --silent
   - yarn lighthousebot https://jameswiens.dev

notifications:
  slack: aretecode:iup7yYHuehxb7jdj20BjpimH
